# Generated by Django 5.1.2 on 2024-11-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavras',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='palavras',
            name='user',
            field=models.ForeignKey(default=10, max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
